swagger: "2.0"
info:
  version: "v1"
  title: Security Group
  description: "Security Group APIs"

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/networkSecurityGroups/":
     get:
       summary: "Query security group list"
       description: "Query security group list"
       operationId: describeNetworkSecurityGroups

       parameters:
         - name: pageNumber
           in: query
           type: integer
           default: 1
           minimum: 1
           description: "Page: 1 by default. Value Range: [1,∞); when the pages exceed total pages, show the last page"
         - name: pageSize
           in: query
           type: integer
           default: 20
           minimum: 10
           maximum: 100
           description: "Paging Size; 20 by default. Value Range: [10, 100]"
         - name: filters
           in: query
           type: array
           items:
             #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
             $ref: "../../common/model/Filter.yaml#/definitions/filter"
           description: |
                  networkSecurityGroupIds - Security group ID list, support multiple IDs
                  networkSecurityGroupNames - Security Group name list, support multiple names
                  vpcId	- VPC ID of Security Group, support single Id

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   networkSecurityGroups:
                     description: "Security group resource information list"
                     type: array
                     items:
                       $ref: "../model/NetworkSecurityGroup.yaml#/definitions/networkSecurityGroup"
                   totalCount:
                     description: "Total Number"
                     type: number
               requestId:
                 description: "Request ID"
                 type: string
         400:
            description: "invalid parameter"
         401:
            description: "Authentication failed"

     #create networkSecurityGroup
     post:
       summary: "Create security group"
       description: "Create security group"
       operationId: createNetworkSecurityGroup
       parameters:
         - name: networkSecurityGroupSpec
           in: body
           required: true
           description: "Create security group request parameter"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/NetworkSecurityGroupSpec.yaml#/definitions/networkSecurityGroupSpec"

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   networkSecurityGroupId:
                     description: "Security group ID"
                     type: string
               requestId:
                 description: "Request ID"
                 type: string
         400:
            description: "invalid parameter"
         404:
            description: "Resource not found"
         500:
            description: "Internal server error"


  "/networkSecurityGroups/{networkSecurityGroupId}":
     #describe networkSecurityGroup
     get:
       summary: Query security group information details
       description: "Query security group information details"
       operationId: describeNetworkSecurityGroup

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   networkSecurityGroup:
                      description: "Security group resource information"
                      $ref: "../model/NetworkSecurityGroup.yaml#/definitions/networkSecurityGroup"
               requestId:
                 description: "Request ID"
                 type: string
         400:
            description: "invalid parameter"
         401:
            description: "Authentication failed"

     #modify networkSecurityGroup
     patch:
       summary: Modify security group attribute
       description: "Modify security group attribute"
       operationId: modifyNetworkSecurityGroup

       parameters:
         - name: modifyNetworkSecurityGroupSpec
           in: body
           required: true
           description: "Modify security group"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/ModifyNetworkSecurityGroupSpec.yaml#/definitions/modifyNetworkSecurityGroupSpec"
       responses:
         200:
           description: OK
           schema:
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

     #delete networkSecurityGroup
     delete:
         summary: Delete security group
         description: "Delete security group"
         operationId: deleteNetworkSecurityGroup

         responses:
           200:
             description: OK
             schema:
               properties:
                 requestId:
                   description: "Request ID"
                   type: string
           400:
             description: invalid parameter
           404:
             description: Resource not found
           500:
             description: Internal server error

  #add security group rules
  "/networkSecurityGroups/{networkSecurityGroupId}:addNetworkSecurityGroupRules":
    post:
      summary: "Add security group rule"
      description: "Add security group rule"
      operationId: addNetworkSecurityGroupRules
      parameters:
        - name: addNetworkSecurityGroupRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/AddNetworkSecurityGroupRulesSpec.yaml#/definitions/addNetworkSecurityGroupRulesSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "Request ID"
                 type: string
        400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
        404:
           description: Resource not found
        409:
           description: SecurityGroup rules not in the same vpc
        500:
           description: Internal server error

  #remove security group rules
  "/networkSecurityGroups/{networkSecurityGroupId}:removeNetworkSecurityGroupRules":
    post:
      summary: "Remove security group rule"
      description: "Remove security group rule"
      operationId: removeNetworkSecurityGroupRules
      parameters:
        - in: body
          name: ruleIds
          description: "Security Group Rule ID List"
          required: true
          schema:
            type: array
            items:
              type: string

      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "Request ID"
                 type: string
        400:
           description: "Request field x.y.z is missing."
        404:
           description: "Target 'xxx' not found; TargetGroup 'xxx' not found."
        500:
           description: "internal server error"
  
  #modify security group rules         
  "/networkSecurityGroups/{networkSecurityGroupId}:modifyNetworkSecurityGroupRules":
    post:
      summary: "Modify security group rule"
      description: "Modify security group rule"
      operationId: modifyNetworkSecurityGroupRules
      parameters:
        - name: modifySecurityGroupRuleSpecs
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyNetworkSecurityGroupRulesSpec.yaml#/definitions/modifySecurityGroupRuleSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "Request ID"
                 type: string
        400:
           description: "invalid parameter"
        404:
           description: "SecurityGroup or SecurityGroupRule not found"
        500:
           description: Internal server error
  
  "/networkSecurityGroups/{networkSecurityGroupId}:associateSecurityGroup":
     post:
       description: "Associate security group APIs"
       operationId: associateSecurityGroup
       x-jdcloud-internal: true
       parameters:
        - name: networkInterfaceIds
          in: body
          required: true
          description: "List of Elastic Network Interface IDs to be associated with security groups, at most 5 security groups to be associated with each Elastic Network Interface"
          schema:
            type: array
            items:
              type: string
       
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

  "/networkSecurityGroups/{networkSecurityGroupId}:disassociateSecurityGroup":
     post:
       description: "Disassociate Security Group APIs"
       operationId: disassociateSecurityGroup
       x-jdcloud-internal: true
       parameters:
        - name: networkInterfaceId
          in: query
          required: true
          type: string
          description: "Elastic Network Interface ID to Be Disassociated by Security Groups"

       responses:
         200:
           description: "Successful operation"
           schema:
             type: object
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  networkSecurityGroupId:
    name: networkSecurityGroupId
    in: path
    required: true
    type: string
    description: NetworkSecurityGroup ID
