swagger: "2.0"
info:
  description: "Monitoring Rules APIs, providing functions such as Create, Query, Modify, Delete Monitoring Rules"
  title: Monitoring Rules APIs
  version: "v1"
consumes:
- application/json
produces:
- application/json

basePath: /regions/{regionId}

paths:
  /alarms:
    ###################### Query Monitoring Rules######################
    get:
      description: "Query monitoring rules, supporting query based on rule status, alarm status, resource ID and product name."
      summary: Query Monitoring Rules
      operationId: describeAlarms
      x-jdcloud-internal: false
      parameters:
        - type: string
          description: "Product Name"
          name: serviceCode
          in: query
        - type: string
          description: "Resource Id"
          name: resourceId
          in: query
        - type: integer
          description: "Rule Alarm Status, 1: Normal, 2: Alarm, 4: Insufficient Data"
          name: status
          in: query
        - type: integer
          description: "Whether it is the rule that is alarming, 0 is neglect, 1 is yes, only one can take effect at the same time as status, isAlarming takes priority to take effect"
          name: isAlarming
          in: query
        - type: integer
          description: "Rule Status: 1 is Enable, 0 is Disable"
          name: enabled
          in: query
        - type: integer
          description: "Page; 1 by default, the value range: [1,∞)"
          name: pageNumber
          in: query
        - type: integer
          description: "Paging Size; 20 by default. Value Range: [10, 100]"
          name: pageSize
          in: query
      responses:
        200:
          description:  OK
          schema:
            properties:
              result:
                properties:
                  alarmList:
                    description: "List of rules"
                    type: array
                    items:
                      $ref: "../model/Alarm.yaml#/definitions/alarm"
                  pageNumber:
                    type: number
                    description: "Page"
                  numberPages:
                    type: number
                    description: "Number of Total Pages"
                  numberRecords:
                    type: number
                    description: "Total Number of Records"
                  pageSize:
                    type: number
                    description: "Paging Size"
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"

    ###################### Create Rules######################
    post:
      description: "Create alarm rules, it can create alarm rules for a certain instance, or it also can create alarm rules for multiple instances at the same time."
      summary: Create Rules
      operationId: createAlarm
      x-jdcloud-internal: false
      parameters:
        - name: Body
          in: body
          description: "Rule Parameter"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/Alarm.yaml#/definitions/createAlarmBody"
      responses:
        200:
          description:  OK
          schema:
            properties:
              result:
                type: object
                properties:
                  alarmIdList:
                    type: array
                    description: "Rule ID List Created"                    
                    items:
                      type: string 
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
          
    ###################### Delete Rules in Batches ######################
    delete:
      description: "Delete alarm rules already created in batches"
      summary: Delete alarm rules already created in batches
      operationId: deleteAlarms
      x-jdcloud-internal: false
      parameters:
        - type: string
          description: For rule id to be deleted, use '\|' to separate multiple rules
          name: ids
          in: query
          required: true
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
          
  /alarms/{alarmId}:
    ###################### Query Rule Details ######################
    get:
      description: "Query Rule Details"
      summary: Query Rule Details
      operationId: describeAlarmsByID
      x-jdcloud-internal: false
      responses:
        200:
          description:  OK
          schema:
            properties:
              result:
                type: object
                properties:
                  alarm:
                    $ref: "../model/Alarm.yaml#/definitions/alarm"    
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
          
    ###################### Modify Rules ######################
    patch:
      description: "Modify alarm rules already created, support to modify alarm rules and notified contact information When the alarm rule is in the status of “Enabled” the alarm rule is allowed to be modified."
      summary: Modify Rules
      operationId: updateAlarm
      x-jdcloud-internal: false
      parameters:
        - name: Body
          in: body
          description: "Rule Parameter"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/Alarm.yaml#/definitions/updateAlarmBody"
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: "Request ID"
              result:
                type: object
                properties:
                  alarmId:
                    description: "Rule ID"
                    type: string
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
         
  "/alarms/{alarmId}:enable":
    ###################### Enable Rules ######################
    post:
      description: "Enable the alarm rule, when the alarm rule is in the status of “Disabled”, the alarm rule can be enabled by using the API."
      summary: Enable rules
      operationId: enableAlarm
      x-jdcloud-internal: false
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
          
  "/alarms/{alarmId}:disable":
    ###################### Disable Rules ######################
    post:
      description: "Disable the alarm rule. After the alarm rule is disabled, the detection of monitoring item data of the instance will be stopped."
      summary: Disable Rules
      operationId: disableAlarm
      x-jdcloud-internal: false
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
          
  /alarmHistory:
    ###################### Query Alarm History ######################
    get:
      description: "Query alarm history, supporting query based on alarm rule ID, resource ID and product name."
      summary: Query Alarm History
      operationId: describeAlarmHistory
      x-jdcloud-internal: false      
      parameters:
      - type: string
        description: "ID of Alarm Rule"
        name: id
        in: query
      - type: string
        description: "Product Name"
        name: serviceCode
        in: query
      - type: string
        description: "Resource Id"
        name: resourceId
        in: query
      - type: string
        description: "Query start time of data, 24 hours ago by default, it can enter long-type time, and it also can enter yyyy-MM-dd'T’HH:mm:ssZ type time"
        name: startTime
        in: query
        required: true
      - type: string
        description: "Query end time of data, current time by default, it can enter long-type time, and it also can enter yyyy-MM-dd'T’HH:mm:ssZ type time"
        name: endTime
        in: query
        required: true
      - type: integer
        description: "Page; 1 by default, the value range: [1,∞)"
        name: pageNumber
        in: query
      - type: integer
        description: "Paging Size; 20 by default. Value Range: [10, 100]"
        name: pageSize
        in: query
      responses:
        200:
          description:  OK
          schema:
            properties:
              result:
                properties:
                  alarmHistoryList:
                    description: "Alarm History List"
                    type: array
                    items:
                      $ref: "../model/Alarm.yaml#/definitions/alarmHistory"
                  pageNumber:
                    type: number
                    description: "Page"
                  numberPages:
                    type: number
                    description: "Number of Total Pages"
                  numberRecords:
                    type: number
                    description: "Total Number of Records"
                  pageSize:
                    type: number
                    description: "Paging Size"
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "invalid parameter"
        500:
          description: "internal server error"
          
# Path General Parameters
parameters:
  regionId:
    type: string
    description: "Region ID"
    name: regionId
    in: path
    required: true
  alarmId:
    type: string
    description: "Rule ID"
    name: alarmId
    in: path
    required: true