swagger: "2.0"
definitions:
  cacheInstance:
    x-jdcloud-module: redis
    title: CacheInstance
    type: object
    properties:
      cacheInstanceId:
        type: string
        description: "Instance ID"
      cacheInstanceName:
        type: string
        description: "Instance Name"
      cacheInstanceClass:
        type: string
        description: "Instance specification code, refer to<a href='https://www.jdcloud.com/help/detail/411/isCatalog/1'>Instance Specification Code</a>"
      cacheInstanceMemoryMB:
        type: integer
        description: "Capacity, Unit: MB"
      cacheInstanceStatus:
        type: string
        description: "Instance status, running: running, error: error, creating: pending, changing: changing, deleting: deleting"
      cacheInstanceDescription:
        type: string
        description: "Instance Description"
      createTime:
        type: string
        format: date-time
        description: "Creation Time"
      azId:
        $ref: "./AzId.yaml#/definitions/azId"
        description: "Az Information"
      vpcId:
        type: string
        description: "ID of VPC"
      subnetId:
        type: string
        description: "ID of Subnet"
      connectionDomain:
        type: string
        description: "Access to the Domain Name"
      port:
        type: integer
        description: "Port"
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: "Billing Information"
      instanceVersion:
        type: string
        description: "Instance Version"
      auth:
        type: boolean
        description: With or Without Password

