swagger: "2.0"
info:
  version: "v1"
  title: CDS APIs
  description: "CDS APIs, provides functions including creating Cloud Disks in batches, querying a Cloud Disk, deleting a Cloud Disk, expanding a Cloud Disk, modifying the Cloud Disk information, and using a snapshot to restore a Cloud Disk."

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/disks":
    ###################### API for Cloud Disk Creation ######################
    post:
      description: |
        -   Create one or more Cloud Disks that are paid by configuration or by service time.
        -   Disk type includes Premium Hdd Cloud Disk and SSD Cloud Disk.
        -   The billing method defaults to paying by configuration.
        -   After creation is completed, the status of the Cloud Disk is available.
        -   The optional parameter snapshot ID is used to create a new disk.
        -   In batch creation, the name of the Cloud Disk is: hard disk name -number, such as myDisk-1 and myDisk-2.
        -   maxCount is the maximum effort, and it is not guaranteed that maxCount can be reached.
      summary: "Create a cloud disk"
      operationId: createDisks
      parameters:
        - name: DiskSpec
          in: body
          required: true
          description: "Create the specification of the cloud disk"
          schema:
            $ref: "../model/DiskSpec.yaml#/definitions/diskSpec"
        - name: maxCount
          in: query
          type: integer
          required: true
          description: "Purchase number of instances; value range: [1,100]"
        - name: clientToken
          in: query
          type: string
          required: true
          description: "Idempotence Check Parameter"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Result Set"
                properties:
                  diskIds:
                    type: array
                    description: "List of Cloud Disk IDs created"
                    items:
                      type: string
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### API for Cloud Disk List Query ######################
    get:
      operationId: describeDisks
      summary: "Query cloud disk list"
      description: |
        -   filters, between multiple filter conditions is logic AND, and multiple values ​​inside each condition is logic OR
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page Number: 1 by default; value range: [1, ∞)"
          
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Paging Size: 20 by default. Value Range: [10, 100]"
          
        - name: tags
          in: query
          description: "Tag Filter Condition"
          type: array
          items:
            $ref: "../model/TagFilter.yaml#/definitions/tagFilter"

        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            diskId - Cloud Disk ID, accurate match, support multiple
            diskType - Type of Cloud Disk, accurate match, support multiple, value: ssd or premium-hdd
            instanceId - ID of the Machine, to which the cloud disk is attached, accurate match, support multiple
            instanceType - Type of the Machine, to which the cloud disk is attached, accurate match, support multiple
            status - Availability Zone, accurate match, support multiple
            az - Status of the cloud disk, accurate match, support multiple
            name - Name of the cloud disk, fuzzy match, support single
            multiAttach - Whether the cloud disk is multi-point attached, accurate match, support multiple
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                type: object
                description: "Query Result Set"
                properties:
                  disks:
                    type: array
                    description: "List of cloud disk details queried"
                    items:
                      $ref: "../model/Disk.yaml#/definitions/disk"
                  totalCount:
                    type: integer
                    description: "Number of cloud disks queried"
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### API for Cloud Disk Details Query ######################
  "/disks/{diskId}":
      get:
        summary: "Query details of a cloud disk"
        description: "Query details of a cloud disk"
        operationId: describeDisk
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Query cloud disk details"
                  properties:
                    disk:
                      $ref: "../model/Disk.yaml#/definitions/disk"
                requestId:
                  type: string
                  description: "Request ID"
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for Single Cloud Disk Deletion ######################
      delete:
        summary: "Delete a single cloud disk"
        description: |
          -   Delete a cloud disk billed by configuration. The disk types include the Premium Hdd Cloud Disk and the SSD Cloud Disk.
          -   After the hard disk is deleted, the cloud disk snapshot can be retained.
          -   When the disk is released, the status of the cloud disk is to-be-attached (Available).
          -   If the disk of the specified ID does not exist, the request will be ignored.
        operationId: deleteDisk
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for Cloud Disk Properties Modification ######################
      patch:
        summary: "Modify cloud disk properties"
        description: "Modify the name or description of the cloud disk, specify either"
        operationId: modifyDiskAttribute
        parameters:
          - name: name
            in: query
            type: string
            description: "Name of the cloud disk: Only Chinese characters, numbers, uppercase and lowercase letters, English underscores '_' and hyphens '-' are allowed. It is not allowed to be blank and shall not exceed 32 characters."
          - name: description
            in: query
            type: string
            description: "Description of the cloud disk: It allows you to enter all characters under UTF-8 encoding, but no more than 256 characters."
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for Cloud Disk Recovery from Snapshot ######################
  "/disks/{diskId}:restore":
      post:
        summary: "Recovering a cloud disk from a snapshot"
        description: |
          -   Data recovery operations can only be executed on the source hard disk, from which the snapshot was taken.
          -   Snapshots can be used for data recovery operations only if the source hard disk is available.
          -   After the cloud disk is restored, the current data will be cleared. Please be cautious.
        operationId: restoreDisk
        parameters:
          - name: snapshotId
            in: query
            type: string
            required: true
            description: "Snapshot ID used to recover the cloud disk"
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for  Capacity Expansion of Cloud Disk ######################
  "/disks/{diskId}:extend":
      post:
        summary: "Cloud disk capacity can only be expanded, and cannot be reduced."
        description: |
          -   Expansion of the cloud disk requires it in available status.
          -   Capacity expansion is not allowed while the disk is creating a snapshot.
        operationId: extendDisk
        parameters:
          - name: diskSizeGB
            in: query
            type: integer
            required: true
            description: "The size of the cloud disk after expansion is in GiB"
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  diskId:
    name: diskId
    in: path
    required: true
    type: string
    description: "Cloud Disk ID"
