swagger: "2.0"
definitions:
  instanceNetworkInterface:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: "Describe instance’s network interface information"
    properties:
      networkInterfaceId:
        type: string
        description: "ENI ID"
      macAddress:
        type: string
        description: "Ethernet Address"
      vpcId:
        type: string
        description: "Virtual Network ID"
      description:
        type: string
        description: "Description"
      securityGroups:
        type: array
        items:
          $ref: "./SecurityGroupSimple.yaml#/definitions/securityGroupSimple"
        description: "Security Group List"
      sanityCheck:
        type: boolean
        description: "Source and target IP address verification, with value 0 or 1"
      primaryIp:
        $ref: "./NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: "Network Interface Primary IP"
      secondaryIps:
        type: array
        items:
          $ref: "./NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: 