swagger: "2.0"
definitions:
  networkInterfaceSpec:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: "Create Network Interface Request Template"
    required:
      - subnetId
      - az
    properties:
      subnetId:
        type: string  
        description: "Subnet ID"
      az:
        type: string  
        description: "Availability Zone, User’s Default Availability Zone"
      primaryIpAddress:
        type: string  
        description: "Network Interface Primary IP"
      secondaryIpAddresses:
        type: array
        items: 
          type: string
        description: "Secondary IP List"
      secondaryIpCount:
        type: integer     
        description: "Amount of Secondary IP Assigned Automatically"
      securityGroups:
        type: array
        items:
          type: string
        description: "Security Group ID List" 
      sanityCheck:
        type: boolean    
        description: "PortSecurity, the value is 0 or 1, 1 by default"
      description:
        type: string   
        description: "Description" 