swagger: '2.0'
info:
  description: "Image Style APIs"
  version: v1
  title: ImageStyle OpenAPI
basePath: '/regions/{regionId}/buckets/{bucketName}'
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Zone ID"
  bucketName:
    name: bucketName
    in: path
    required: true
    type: string
    description: "Bucket Name"
tags:
  - name: ImageStyle
    description: "Image Style"
paths:
  '/imageStyles':
    get:
      tags:
        - ImageStyle
      description: "Image Style List"
      operationId: listImageStyle
      parameters:
        - name: styleName
          in: query
          description: "Query by Style Name"
          type: string
        - name: pageNumber
          in: query
          description: "Data Page"
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: "Number of Data Per Page"
          type: integer
          default: 10
      responses:
        '200':
          description: success
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyleQueryResult'
    post:
      tags:
        - ImageStyle
      description: "Add Image Style"
      operationId: createImageStyle
      parameters:
        - name: imageStyle
          in: body
          description: "Style Parameter"
          x-jdcloud-tiered: false
          schema:
            $ref: '#/definitions/ImageStyle'
      responses:
        '200':
          description: success
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyleID'
                
  '/imageStyles/{id}':
    parameters:
      - name: id
        in: path
        type: integer
        format: int64
        required: true
        description: "Image Style ID"
    get:
      tags:
        - ImageStyle
      description: "Image Style Details"
      operationId: getImageStyle
      responses:
        '200':
          description: successful operation
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyle'
    delete:
      tags:
        - ImageStyle
      description: "Delete Image Style"
      operationId: deleteImageStyle
      responses:
        '200':
          description: successful operation
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
    put:
      tags:
        - ImageStyle
      description: "Modify Image Style"
      operationId: updateImageStyle
      parameters:
        - name: imageStyle
          in: body
          description: "Style Parameter Needing Modification"
          x-jdcloud-tiered: false
          schema:
            $ref: '#/definitions/ImageStyle'
      responses:
        '200':
          description: successful operation
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
                
  '/imageStyles/count':
    get:
      tags:
        - ImageStyle
      description: "Total Number of Image Styles"
      operationId: countImageStyle
      parameters:
        - name: styleName
          in: query
          description: "Query by Style Name"
          type: string
      responses:
        '200':
          description: success
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyleCount'
definitions:
  ImageStyle:
    x-jdcloud-module: mps
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: "Image Style ID"
        readOnly: true
      ucUserId:
        type: string
        description: "User ID"
        readOnly: true
      styleName:
        type: string
        description: "Image Style Name"
      params:
        type: string
        description: "Image Style Parameter"
      paramAlias:
        type: string
        description: "Image Style Parameter Alias"
      regionId:
        type: string
        description: "Zone"
        readOnly: true
      bucketName:
        type: string
        description: "Bucket"
        readOnly: true
      status:
        type: integer
        format: byte
        description: "Image Style Status"
        default: 1
      modifyTime:
        type: string
        format: date
        description: "Modification Time"
        readOnly: true
      createdTime:
        type: string
        format: date
        description: "Creation Time"
        readOnly: true
        
  ImageStyleQueryResult:
    x-jdcloud-module: mps
    type: object
    properties:
      styleName:
        description: "Query by Style Name"
        type: string
      pageNumber:
        description: "Data Page"
        type: integer
        default: 1
      pageSize:
        description: "Number of Data Per Page"
        type: integer
        default: 10
      imageStyleList:
        type: array
        description: "Image Style List"
        items:
          $ref: '#/definitions/ImageStyle'
          
  ImageStyleID:
    x-jdcloud-module: mps
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: "Image Style ID"
        
  ImageStyleCount:
    x-jdcloud-module: mps
    type: object
    properties:
      styleCount:
        type: integer
        description: "Total Number of Image Styles"
schemes:
  - http
