---
swagger: '2.0'
info:
  description: "Media Processing Service API, including screenshots, transcoding, media processing message notifications, etc. This document details the media processing API and usage, which is suitable for developers."
  version: "v1"
  title: "Media Processing APIs"
basePath: "/regions/{regionId}"
host: "mps.jdcloud.com"
tags:
- name: "thumbnail"
  description: "Screenshot"
- name: "transcode"
  description: "Transcoding"
- name: "notification"
  description: "Message Notification"
parameters:
  regionId:
    name: "regionId"
    in: "path"
    required: true
    type: "string"
    description: "region id"
paths:
  /thumbnail:
    post:
      tags:
      - "thumbnail"
      summary: "Create MPS thumbnail task"
      description: "Create a screenshot task, return the task ID when the creation is successful. This API is used to capture the screen at a specified time."
      operationId: "createThumbnailTask"
      parameters:
      - name: "body"
        in: "body"
        x-jdcloud-tiered: false
        schema:
          $ref: "#/definitions/ThumbnailTask"
      responses:
        200:
          x-jdcloud-tiered: false
          description: "Successful"
          schema:
            properties:
              requestId:
                type: "string"
              result:
                $ref: "#/definitions/ThumbnailTaskID"
    get:
      tags:
      - "thumbnail"
      summary: "List MPS thumbnail task"
      description: "Query the screenshot task and return the task list that meets the query criteria."
      operationId: "listThumbnailTask"
      parameters:
      - name: "status"
        in: "query"
        type: "string"
        description: "Task Status (PENDING, RUNNING, SUCCESS, FAILED)"
        required: false
        enum: 
        - PENDING
        - RUNNING
        - SUCCESS
        - FAILED
      - name: "begin"
        in: "query"
        type: "string"
        description: "Start Time, Time Format(GMT): yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
        required: false
      - name: "end"
        in: "query"
        type: "string"
        description: "End Time, Time Format(GMT): yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
        required: false
      - name: "marker"
        in: "query"
        type: "string"
        description: "Query Tag"
        required: false
      - name: "limit"
        in: "query"
        description: "Number of Query Records [1, 1000]"
        type: "integer"
        default: 1000
        required: false
      responses:
        200:
          description: "Successful"
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: "string"
              result:
                $ref: "#/definitions/ThumbnailQuery"
  /thumbnail/{taskId}:
    parameters:
    - name: "taskId"
      in: "path"
      description: "task id"
      required: true
      type: "string"
    get:
      tags:
      - "thumbnail"
      summary: "Get MPS thumbnail task"
      description: "Acquire the screenshot task based on the task ID."
      operationId: "getThumbnailTask"
      responses:
        200:
          description: "OK"
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: "string"
              result:
                $ref: "#/definitions/ThumbnailTask"
#   /thumbnail/{taskId}/status:
#     parameters:
#     - name: "taskId"
#       in: "path"
#       description: "task id"
#       required: true
#       type: "string"
#     put:
#       tags: 
#       - "thumbnail"
#       summary: "Update thumbnail task status"
#       description: "Update thumbnail task status"
#       operationId: "putThumbnailTaskStatus"
#       parameters: 
#       - name: "body"
#         in: "body"
#         x-jdcloud-tiered: false
#         schema:
#           $ref: "#/definitions/ThumbnailStatus"
#       responses:
#         200:
#           description: "OK"
    
  /notification:
    put:
      tags:
      - "notification"
      summary: "Set MPS Notification"
      description: "Set the media processing notification. Endpoint will be verified when setting the Notification, and SubscriptionConfirmation(x-jdcloud-message-type head) will be sent to the endpoint, which requests base64 encoding for the Message content that are then to be returned to the system (body) for verification."
      operationId: "setNotification"
      parameters:
      - name: "body"
        in: "body"
        x-jdcloud-tiered: false
        schema:
          $ref: "#/definitions/Notification"
      responses:
        200:
          description: "Successful"
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: "string"
    get:
      tags:
      - "notification"
      summary: "Get MPS Notification"
      description: "Acquire Screenshot Notification"
      operationId: "getNotification"
      responses:
        200:
          description: "Successful"
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: "string"
              result: 
                $ref: "#/definitions/Notification"
#   /transcode/{taskId}/status:
#     parameters:
#     - name: "taskId"
#       in: "path"
#       required: true
#       description: "Task Id"
#       type: "string"
#     put:
#       tags:
#       - "transcode"
#       summary: "PUT MPS Transcode Status"
#       description: "Update Transcoding Task Status"
#       operationId: "putMpsTranscodeStatus"
#       parameters:
#       - name: "body"
#         in: "body"
#         x-jdcloud-tiered: false
#         schema:
#           $ref: "#/definitions/TranscodeStatus"
#       responses:
#         200:
#           description: "Successful"

definitions:
  Notification:
    x-jdcloud-module: mps
    type: "object"
    required:
    - "enabled"
    properties:
      enabled:
        type: "boolean"
        example: true
        description: "Whether to enable notifications"
      endpoint:
        type: "string"
        example: "http://xxx.yyy.com/notifications"
        description: "Notify endpoint, support http:// and https:// currently"
      events:
        type: "array"
        description: "Collection of events that trigger notifications (mpsTranscodeComplete, mpsThumbnailComplete)"
        items:
          type: "string"
          enum:
          - "mpsTranscodeComplete"
          - "mpsThumbnailComplete"
        example: [mpsTranscodeComplete, mpsThumbnailComplete]
      notifyStrategy:
        type: "string"
        description: "Retry policy, BACKOFF_RETRY: Backoff retry strategy, retry 3 times. The interval between each retry is a random value between 10 seconds and 20 seconds; EXPONENTIAL_DECAY_RETRY: exponential decay retry, retry 176 times.  The interval between each retry is incremented to 512 seconds, and the total retry time is 1 day; the specific interval for each retry is: 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 512 ... 512 seconds (167 512s in total)"
        enum: 
        - "BACKOFF_RETRY"
        - "EXPONENTIAL_DECAY_RETRY"
        default: "BACKOFF_RETRY"
      notifyContentFormat:
        type: "string"
        description: "Describes the format of the message pushed to the Endpoint; JSON: contains the message text and message properties; SIMPLIFIED: message body is the message released by the user, excluding any properties information"
        enum:
        - "JSON"
        - "SIMPLIFIED"
        default: "SIMPLIFIED"
  ThumbnailTask:
    x-jdcloud-module: mps
    type: "object"
    required:
    - "source"
    - "target"
    properties:
      taskID:
        type: "string"
        description: "Task ID (readonly)"
        readOnly: true
      status:
        type: "string"
        description: "Status (SUCCESS, ERROR, PENDDING, RUNNING) (readonly)"
        readOnly: true
        enum:
        - "SUCCESS"
        - "ERROR"
        - "PENDDING"
        - "RUNNING"
      errorCode:
        type: "integer"
        description: "Error Code (readonly)"
        readOnly: true
      createdTime:
        type: "string"
        description: "Task Creation Time, Format (GMT): yyyy-MM-dd’T’HH:mm:ss.SSS’Z’  (readonly)"
        readOnly: true
      lastUpdatedTime:
        type: "string"
        description: "Task Creation Time, Format (GMT): yyyy-MM-dd’T’HH:mm:ss.SSS’Z’  (readonly)"
        readOnly: true
      source:
        $ref: "#/definitions/ThumbnailTaskSource"
      target:
        $ref: "#/definitions/ThumbnailTaskTarget"
      rule:
        $ref: "#/definitions/ThumbnailTaskRule"
  ThumbnailTaskSource:
    x-jdcloud-module: mps
    type: "object"
    description: "Video Screenshot Source File Parameters"
    required:
    - "bucket"
    - "key"
    properties:
      bucket:
        type: "string"
        description: "Enter the Bucket of Video Information"
      key:
        type: "string"
        description: "Enter the Key of Video Information"
  ThumbnailTaskTarget:
    x-jdcloud-module: mps
    type: "object"
    description: "Video Screenshot Target File Parameters"
    required:
    - "destBucket"
    properties:
      destBucket:
        type: "string"
        description: "Enter the bucket that saves target file"
      destKeyPrefix:
        type: "string"
        description: "Prefix of Key of Target Screenshot, 'Prefix-taskID-%04d(num).(format)', default: sourceKey"
        default: sourceKey
      format:
        type: "string"
        description: "Format of Target Screenshot default: jpg"
        default: jpg
        enum:
        - "jpg"
        - "png"
        - "webp"
      widthInPixel:
        type: "integer"
        description: "The width of the target screenshot shall be output according to the actual resolution if the actual resolution of the video is less than the target resolution. Default: 0 means the height of source video. Others [8, 4096]"
        default: 0
      heightInPixel:
        type: "integer"
        description: "The height of the target screenshot shall be output according to the actual resolution if the actual resolution of the video is less than the target resolution. Default:  0 means the height of source video. Others [8, 4096]"
        default: 0
      keys:
        type: "array"
        description: "Set of Key of Target Screenshot (readonly)"
        readOnly: true
        items:
          type: "string"
  ThumbnailTaskRule:
    x-jdcloud-module: mps
    type: "object"
    description: "Video Screenshot Rule Parameters"
    properties:
      mode: 
        type: "string"
        description: "Screenshot mode, single screenshot: single, multiple screenshots: multi, average: average, default: single"
        default: single
        enum:
        - "single"
        - "multi"
        - "average"
      keyFrame:
        type: "boolean"
        description: "Whether to enable keyframe screenshots. Default: true"
        default: true
      startTimeInSecond:
        type: "integer"
        description: "Start time of generated screenshot, unavailable when mode=average. Default:0"
        default: 0
      endTimeInSecond:
        type: "integer"
        description: "End time of generated screenshot, unavailable when mode=single/average, and it shall not be less than startTimeInSecond. Default: -1 (representing video duration)"
        default: -1
      count:
        type: "integer"
        description: "Number of screenshots, unavailable when mode=single. Default:1"
        default: 1
  ThumbnailTaskID:
    x-jdcloud-module: mps
    type: "object"
    properties:
      taskID:
        type: "string"
  ThumbnailQuery:
    x-jdcloud-module: mps
    type: "object"
    properties:
      status:
        type: "string"
        description: "Status (SUCCESS, ERROR, PENDDING, RUNNING)"
        enum:
        - "SUCCESS"
        - "ERROR"
        - "PENDDING"
        - "RUNNING"
      begin:
        type: "string"
        description: "Query start time, format (GMT): yyyy-MM-dd’T’HH:mm:ss.SSS’Z’"
      end:
        type: "string"
        description: "Query End Time, Time Format (GMT): yyyy-MM-dd’T’HH:mm:ss.SSS’Z’"
      marker:
        type: "string"
        description: "Marker of this request, starting position of tag query, taskID here"
      limit:
        type: "integer"
        description: "The maximum number of elements in the task list returned by this request, valid value: [1-1000], default: 1000"
        default: 1000
      nextMarker:
        type: "string"
        description: "Get the marker value to be passed on the next page (taskID here), only when isTruncated is true (data not all returned), it appears (readonly)"
        readOnly: true
      truncated:
        type: "boolean"
        description: "Indicate whether the returned data is truncated. true means there is data behind the page, that is, the data is not all returned; false means that this is the last page, that is, the data has all been returned (readonly)"
        readOnly: true
      taskList:
        type: "array"
        description: "Returned Task List (readonly)"
        readOnly: true
        items:
          $ref: "#/definitions/ThumbnailTask"
  ThumbnailStatus:
    x-jdcloud-module: mps
    type: "object"
    required: 
    - "status"
    properties:
      status:
        type: "string"
        description: "Status (SUCESS, ERROR, PENDDING, RUNNING)"
        enum: 
        - "SUCESS"
        - "ERROR"
        - "PENDDING"
        - "RUNNING"
      errorCode:
        type: "integer"
        description: "Error Code"
      count:
        type: "integer"
        description: "Number of screenshot files generated when it is successful"
  TranscodeStatus:
    x-jdcloud-module: mps
    type: "object"
    required: 
    - "status"
    properties:
      status:
        type: "string"
        description: "Status (SUCESS, ERROR, PENDDING, RUNNING)"
        enum: 
        - "SUCESS"
        - "ERROR"
        - "PENDDING"
        - "RUNNING"
      errorCode:
        type: "integer"
        description: "Error Code"
      notifyMessage:
        type: "string"
        description: "Notification message, called by Work, temporary solution"
schemes:
 - http