swagger: "2.0"
info:
  version: "v1"
  title: Profile Single Label Output APIs
  description: Profile Single Label Output APIs

basePath: /regions/{regionId}/profile

paths:
  "/getProfile":
    ###################### Profile Single Label Output APIs Query profile information of the corresponding user according to deviceId
        get:
              description: Query profile information of the corresponding user according to deviceId
              operationId: getProfile
              x-jdcloud-internal: false
              parameters:
                - name: id
                  in: query
                  required: true
                  type: string
                  description: deviceId, mobile, etc., multiple ids are separated by English commas
                - name: type
                  in: query
                  required: true
                  type: string
                  description: "data type, only one type can be queried, support type: mobile, idfa, imei, md5_idfa, md5_imei"
                - name: labelCode
                  in: query
                  required: true
                  type: string
                  description: Profile Label Number, multiple profile labels are separated by English commas
              responses:
                200:
                  description: OK
                  schema:
                    properties:
                      result:
                        properties:
                          status:
                            type: boolean
                            description: True is success, false is failure
                          message:
                            type: string
                            description: "Description Information"
                          data:
                            type: string
                            description: The string is serialized by Map<String, Map<String,String>>. It needs to be reconverted before use. Key is deviceId, and value is the content corresponding to the profile label. The key of inner map is the label code of the profile, while the value is the one corresponding to the profile
                      requestId:
                        type: string
                        description: Request ID, it is different at each time
                500:
                  description: "Internal server error"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"