swagger: "2.0"
definitions:
  dwDatabaseInfo:
    x-jdcloud-module: xdata
    title: DwDatabaseInfo
    type: object
    properties:
      owner:
        type: string
        description: "Owner"
      comments:
        type: string
        description: "Description Information"
      databaseName:
        type: string
        description: "Database Name"