swagger: "2.0"
definitions:
  dwTable:
    x-jdcloud-module: xdata
    title: DwTable
    type: object
    properties:
      id:
        type: integer
        description: "Database ID"
      userName:
        type: string
        description: "User Name"
      dbName:
        type: string
        description: "Database Name"
      tableName:
        type: string
        description: "Table Name"
      createTime:
        type: string
        description: "Creation Time"
      lastUpdateTime:
        type: string
        description: "Last Update Time"
      physicalStorageCapacity:
        type: string
        description: "Physical Storage"
      category:
        type: string
        description: "Category"
      source:
        type: string
        description: "Source"
      owner:
        type: string
        description: "Owner"
      hiveFileFormat:
        type: string
        description: "File Storage Type"
      encryption:
        type: string
        description: "Is it encrypted or not"
      location:
        type: string
        description: "Location"
      comments:
        type: string
        description: "Description Information"
      hiveObjectPrivileges:
        $ref: "../model/DwHiveObjectPrivileges.yaml#/definitions/dwHiveObjectPrivileges"
        description: "Hive Table Permission Information"
      parameters:
        description: "Parameter"
        type: object