swagger: "2.0"
definitions:
  createSubUserInfo:
    x-jdcloud-module: iam
    required:
      - name
      - password
      - phone
      - email
      - createAk
    properties:
      name:
        type: string
        description: "Sub-account User Name, 4-20 numbers, letters, Chinese characters, underlines and line-throughs"
      description:
        type: string
        description: "Description, 0~256 characters"
      password:
        type: string
        description: "Password, 6-20 bits, containing at least one letters and at least one number or half-width character"
      phone:
        type: string
        description: "Mobile Number, Area Code-Mobile Number, at present only support 0086-Chinese mobile number"
      email:
        type: string
        description: "Email"
      createAk:
        type: boolean
        description: "Create accessKey or Not"
