swagger: "2.0"
definitions:
  resultMsg:
    x-jdcloud-module: iam
    properties:
      errorCode:
        type: string
        description: "Wrong Encoding"
      errorMsg:
        type: string
        description: "Wrong Information"