swagger: "2.0"
info:
  version: "v1"
  title: Image
  description: "related interfaces on machine image operations"

basePath: /regions/{regionId}

paths:
  "/images/{imageId}":
    ###################### The details interface of the image ######################
    get:
      description: |
        Query image details.
      operationId: describeImage
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  image:
                    description: "Image Details"
                    $ref: "../model/Image.yaml#/definitions/image"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Delete image API ######################
    delete:
      description: |
        Delete a private image that only allows you to operate your personal private image.
        If the image is shared to other users, the image can be deleted only when the sharing is released.
      operationId: deleteImage
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images":
    ###################### Image List API ######################
    get:
      description: |
        Query the image information list. <br>
        This API allows you to query an public image of JD Cloud, a third-party image, a private image, or an image that other users share to you. <br>
        This API supports paging query with 20 items per page by default.
      operationId: describeImages
      parameters:
        - name: imageSource
          in: query
          type: string
          description: "Image source, if no ids parameter is specified, this parameter is required to pass; value range: public, shared, thirdparty, private"
        - name: platform
          in: query
          type: string
          description: "Operating system platform, range of values: Windows Server, CentOS, Ubuntu"
        - name: ids
          in: query
          type: array
          items:
            type: string
          description: "Image ID list, if this parameter is specified, other parameters can be null"
        - name: rootDeviceType
          in: query
          type: string
          description: "Image-supported system disk types, [ScanDisk, click Disk]"
        - name: status
          in: query
          type: string
          description: "<a href='https://www.jdcloud.com/help/detail/3871/isCatalog/1'>refer to image status</a>"
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: "Page; 1 by default"
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: "Paging Size; 20 by default; Value range[10, 100] "
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  images:
                    type: array
                    description: "Image Details"
                    items:
                      $ref: "../model/Image.yaml#/definitions/image"
                  totalCount:
                    type: integer
                    description: "Quantity"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}/constraints":
    ###################### Query Image Restriction API ######################
    get:
      description: |
        Query the instance type limit of the image. <br>
        This API allows you to view the type of specifications that are not supported by the image. Only the public image, the third-party image has a specification type restriction, and the private image of the individual does not have this limit.
      operationId: describeImageConstraints
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  imageConstraints:
                    type: object
                    description: "Image Restriction"
                    $ref: "../model/ImageConstraint.yaml#/definitions/imageConstraint"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/imageConstraints":
    ###################### Batch Query Image Limits ######################
    get:
      description: |
        Batch query image specification type constraints. <br>
        This API allows you to view the type of specifications that are not supported by the image. Only the public image, the third-party image has a specification type restriction, and the private image of the individual does not have this limit.
      operationId: describeImageConstraintsBatch
      parameters:
        - name: ids
          in: query
          type: array
          items:
            type: string
          description: "Image ID List"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  imageConstraints:
                    type: array
                    items:
                      $ref: "../model/ImageConstraint.yaml#/definitions/imageConstraint"
                    description: "Image Restriction"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:share":
    ###################### Shared Image ######################
    post:
      description: |
        Shared Image allows you to operate only your private image, and a single image can be shared for up to 20 JD Cloud accounts. <br>
        The packaging image does not currently support sharing.
      operationId: shareImage
      parameters:
        - name: pins
          in: query
          type: array
          items:
            type: string
          description: "The account that needs to be shared"
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:unshare":
    ###################### Cancel Shared Image ######################
    post:
      description: |
        Unshared images only allow you to operate your personal private image.
      operationId: unShareImage
      parameters:
        - name: pins
          in: query
          type: array
          items:
            type: string
          description: "The account that needs to be cancelled"
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}/members":
    ###################### Query Image Shared Account List ######################
    get:
      description: |
        Query the image-shared account list, allowing  you to operate your personal private image only.
      operationId: describeImageMembers
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  pins:
                    type: array
                    description: "user Pin list"
                    items:
                      type: string
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:convertImage":
    ###################### Image Transition ######################
    post:
      description: |
        Internal APIs. <br>
        Image conversion, only the conversion of the image from the LocalDisk to the cloudDisk type is supported, allowing  only your personal private image to be operated.
      operationId: convertImage
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  imageId:
                    type: string
                    description: "ID of the New Image after Conversion"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images:copyImages":
    ###################### The inter-zone image replication ######################
    post:
      description: |
        Image inter-domain replication, copy private images to other regions, allowing  you to operate your private image only. <br>
        Only images of the Cloud Disk Service of system disk are supported.
      operationId: copyImages
      parameters:
        - name: sourceImageIds
          in: query
          type: array
          items:
            type: string
          required: true
          description: "Source Image ID"
        - name: destinationRegion
          in: query
          type: string
          required: true
          description: "Target Area"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  copyImages:
                    type: array
                    description: "source image and target image mapping relationships"
                    items:
                      $ref: "../model/CopyImage.yaml#/definitions/copyImage"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/images/{imageId}:modifyImageAttribute":
    ###################### Modify Image Information ######################
    post:
      description: |
        Modify the image information, including name and description; Only allow your personal private image to be operated.
      operationId: modifyImageAttribute
      parameters:
        - name: name
          in: query
          type: string
          description: "Name, <a href='https://www.jdcloud.com/help/detail/3870/isCatalog/1'>Refer to the public parameter specification </a>."
        - name: description
          in: query
          type: string
          description: "Description, <a href='https://www.jdcloud.com/help/detail/3870/isCatalog/1'>Refer to the public parameter specification</a>."
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  imageId:
    name: imageId
    in: path
    required: true
    type: string
    description: "Image ID"
