swagger: "2.0"
info:
  version: "v1"
  title: Start Template
  description: "Start Template APIs"

basePath: /regions/{regionId}

paths:
  "/instanceTemplates":
    ###################### Create Start Template API ######################
    post:
      description: |
        Create a start-up template for a specified parameter. The starting template contains most of the configuration parameters when creating VM, avoiding repetitive work when creating VM each time. <br>
        If you create VM using the starting template, and if certain specified parameters conflict with the parameters in the template, then the newly specified parameters will replace the parameters in the template. <br>
        If you create VM using the starting template, the dataDisks parameter in the template will fail if it is specified that the image ID is not consistent with the image ID in the template. <br>
        If the user creates VM with an availability group (Ag), the parameters in the template associated with the Ag are not adjustable, and only the template should prevail.
      operationId: createInstanceTemplate
      x-jdcloud-internal: true
      parameters:
        - name: instanceTemplateData
          in: body
          required: true
          description: "Start template data"
          schema:
            $ref: "../model/InstanceTemplateSpec.yaml#/definitions/instanceTemplateSpec"
        - name: name
          in: query
          type: string
          required: true
          description: "Name of the Start Template, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification </a>."
        - name: description
          in: query
          type: string
          description: "Description of the Start Template, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification </a>."
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceTemplateId:
                    type: string
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Start Template List API ######################
    get:
      description: |
        Query start template list
      operationId: describeInstanceTemplates
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: "Page; 1 by default"
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: "Page size; it is 20 by default; value range[10, 100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            name - Start template name, fuzzy match, multiple support
            instanceTemplateId-Start template ID, exact match, multiple support
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceTemplates:
                    type: array
                    items:
                      $ref: "../model/InstanceTemplate.yaml#/definitions/instanceTemplate"
                  totalCount:
                    type: number
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/instanceTemplates/{instanceTemplateId}":
    ######################Start Template Detail API ######################
    get:
      description: |
        Query start template details
      operationId: describeInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                $ref: "../model/InstanceTemplate.yaml#/definitions/instanceTemplate"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ######################Delete Start Template API ######################
    delete:
      description: |
        Delete a Start Template
      operationId: deleteInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ######################Modify Start Template Information API ######################
    patch:
      description: |
        Modify the information about a start template, including name and  description
      operationId: updateInstanceTemplate
      x-jdcloud-internal: true
      parameters:
        - name: description
          in: query
          type: string
          description: "Template description, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification</a>."
        - name: name
          in: query
          type: string
          description: "Template name, <a href='http://docs.jdcloud.com/virtual-machines/api/general_parameters'>Refer to the public parameter specification</a>."
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"


  "/instanceTemplates/{instanceTemplateId}:verify":
    ###################### API for Verifing the Availability of a Start Template ######################
    get:
      description: |
        Verify the availability of a start template
      operationId: verifyInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"


# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  instanceTemplate:
    name: instanceTemplateId
    in: path
    required: true
    type: string
    description: "Start template ID"
