swagger: "2.0"
info:
  version: "v1"
  title: SSH Key Pair
  description: "SSH Key Pair APIs"

basePath: /regions/{regionId}

paths:
  "/keypairs":
    ###################### Create ssh Key Pair ######################
    post:
      description: |
        Create ssh key pair. The public key section is stored in JD Cloud and returned to the PKCS # 8 format private key that is not encrypted. You have only one opportunity to save your private key. Please keep it properly. <br>
        An error will occur if the key pair name already exists.
      operationId: createKeypair
      x-jdcloud-internal: true
      parameters:
        - name: keyName
          type: string
          in: query
          required: true
          description: |
            The key pair name needs to be globally unique. <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  keyName:
                    type: string
                    description: "Key Pair Name"
                  privateKey:
                    type: string
                    description: "The private key of the key pair, in PEM PKCS # 8 format."
                  keyFingerprint:
                    type: string
                    description: "The fingerprint of the key pair, based on the public key fingerprint format defined in RFC4716, the MD5 information digest algorithm is adopted."
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Query ssh Key Pair List ######################
    get:
      description: |
        Query secret key pairs in batches. <br>
        This API supports paging query with 20 items per page by default.
      operationId: describeKeypairs
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: "Page; 1 by default"
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: "Paging size; 20 by default; Value range[10, 100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            keyNames-Key pair name, exact match, multiple supported
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  keypairs:
                    type: array
                    items:
                      $ref: "../model/Keypair.yaml#/definitions/keypair"
                  totalCount:
                    type: number
                    description: "Total data number"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/keypairs:import":
    ###################### Import ssh Key Pair ######################
    post:
      description: |
        Import the public key part of the key pair generated by other tools. <br>
        An error will occur if the key pair name already exists.
      operationId: importKeypair
      x-jdcloud-internal: true
      parameters:
        - name: keyName
          in: query
          type: string
          required: true
          description: |
            The key pair name needs to be globally unique. <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
        - name: publicKey
          in: query
          type: string
          required: true
          description: "Public Key of Key Pair"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  keyName:
                    type: string
                    description: "Key Pair Name"
                  keyFingerprint:
                    type: string
                    description: "The fingerprint of the key pair, based on the public key fingerprint format defined in RFC4716, the MD5 information digest algorithm is adopted."
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/keypairs/{keyName}":
    ###################### Delete ssh Key Pair ######################
    delete:
      description: |
        Remove ssh key pair.
      operationId: deleteKeypair
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  keyName:
    name: keyName
    in: path
    required: true
    type: string
    description: "Key Pair Name"
