swagger: "2.0"
info:
  version: "v1"
  title: "Advanced Anti-DDoS Report APIs"
  description: "Advanced Anti-DDoS Report APIs, including CC defense, DDos protection, and forwarding traffic"

basePath: /regions/{regionId}

paths:
  /charts:DDoSGraph:
    get:
      description: "DDos Protection Report"
      operationId: describeDDoSGraph
      parameters:
        - name: startTime
          in: query
          type: string
          required: true
          description: "Start time, up to the latest 60 days, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
        - name: endTime
          in: query
          type: string
          required: true
          description: "Search end time, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
        - name: instanceId
          in: query
          type: array
          items:
            type: string
          description: "Advanced Anti-DDoS Instance ID, 0 or more can be transferred"
          required: false
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  postProtect:
                    type: array
                    items:
                      type: number
                      format: float
                  preProtect:
                    type: array
                    items:
                      type: number
                      format: float
                  time:
                    type: array
                    items:
                      type: integer
                      format: int64
                  unit:
                    type: string
                    description: "Traffic Unit"
              requestId:
                type: string
  /charts:fwdGraph:
    get:
      description: "Forwarding Traffic Report"
      operationId: describeFwdGraph
      parameters:
        - name: startTime
          in: query
          type: string
          required: true
          description: "Start time, up to the latest 60 days, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
        - name: endTime
          in: query
          type: string
          required: true
          description: "Search end time, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
        - name: instanceId
          in: query
          type: array
          items:
            type: string
          description: "Advanced Anti-DDoS Instance ID, 0 or more can be transferred"
          required: false
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  forwardRecord:
                    type: array
                    items:
                      type: number
                      format: float
                  time:
                    type: array
                    items:
                      type: integer
                      format: int64
                  unit:
                    type: string
                    description: "Traffic Unit"
              requestId:
                type: string
  /charts:CCGraph:
    get:
      description: "Forwarding Traffic Report"
      operationId: describeCCGraph
      parameters:
        - name: startTime
          in: query
          type: string
          required: true
          description: "Start time, up to the latest 60 days, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
        - name: endTime
          in: query
          type: string
          required: true
          description: "Search end time, UTC time, format: yyyy-MM-dd'T'HH:mm:ssZ"
        - name: instanceId
          in: query
          type: array
          items:
            type: string
          description: "Advanced Anti-DDoS Instance ID, 0 or more can be transferred"
          required: false
        - name: subDomain
          in: query
          type: array
          items:
            type: string
          description: "Rule Domain Name, 0 or more can be transferred"
          required: false
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  postProtect:
                    type: array
                    items:
                      type: integer
                      format: int64
                  preProtect:
                    type: array
                    items:
                      type: integer
                      format: int64
                  time:
                    type: array
                    items:
                      type: integer
                      format: int64
                  unit:
                    type: string
                    description: "Traffic Unit"
              requestId:
                type: string
# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"