swagger: "2.0"
info:
  version: "v1"
  title:  Non Web Forwarding Configuration APIs
  description: "Non Web Forwarding Configuration APIs"

basePath: /regions/{regionId}

paths:
  /instances/{instanceId}/forwardRules:
    get:
      description: "Search the non-web forwarding configuration under an instance"
      operationId: describeForwardRules
      parameters:
        - name: pageNumber
          in: query
          type: integer
          required: false
          description: "Page Number: 1 by default"
        - name: pageSize
          in: query
          type: integer
          required: false
          description: "Paging Size: 20 by default; value range [10, 100]"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    type: array
                    items:
                      $ref: "../model/ForwardRule.yaml#/definitions/forwardRule"
                  totalCount:
                    type: integer
              requestId:
                type: string
        404:
          description: NOT_FOUND
    post:
      description: "Add a non-web service rule"
      operationId: createForwardRule
      parameters:
        - name: forwardRuleSpec
          in: body
          description: "Add non-web service rule request parameters"
          required: true
          schema:
            $ref: "../model/ForwardRuleSpec.yaml#/definitions/forwardRuleSpec"
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
        400:
          description: BAD_REQUEST
        404:
          description: NOT_FOUND
        500:
          description: INTERNAL_SERVER_ERROR

  /instances/{instanceId}/forwardRules/{forwardRuleId}:
    get:
      description: "Search a non-web service rule"
      operationId: describeForwardRule
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    $ref: "../model/ForwardRule.yaml#/definitions/forwardRule"
              requestId:
                type: string
        404:
          description: NOT_FOUND
    patch:
      description: "Update a non-web service rule"
      operationId: modifyForwardRule
      parameters:
        - name: forwardRuleSpec
          in: body
          description: "Update non-web service rule parameters"
          required: true
          schema:
            $ref: "../model/ForwardRuleSpec.yaml#/definitions/forwardRuleSpec"
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
        400:
          description: BAD_REQUEST
        404:
          description: NOT_FOUND
        500:
          description: INTERNAL_SERVER_ERROR
    delete:
      description: "Delete a non-web service rule"
      operationId: deleteForwardRule
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string

  /instances/{instanceId}/forwardRules/{forwardRuleId}:protect:
    post:
      description: "Switch non-web service rules into defense status"
      operationId: switchForwardRuleProtect
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
        404:
          description: NOT_FOUND
        500:
          description: INTERNAL_SERVER_ERROR

  /instances/{instanceId}/forwardRules/{forwardRuleId}:origin:
    post:
      description: "Switch non-web service rules into back-to-origin status"
      operationId: switchForwardRuleOrigin
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
        404:
          description: NOT_FOUND
        500:
          description: INTERNAL_SERVER_ERROR

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: "Instance ID"
  forwardRuleId:
    name: forwardRuleId
    in: path
    required: true
    type: string
    description: "Forwarding Rule ID"