swagger: "2.0"
definitions:
  disk:
    x-jdcloud-module: disk
    type: object
    description: "Cloud Disk Service Details"
    properties:
      diskId:
        type: string
        description: "Cloud Disk Service ID"
      az:
        type: string
        description: "Available Zone, to which the cloud disk belongs"
      name:
        type: string
        description: "Name of the cloud disk only allows Chinese characters, numbers, uppercase and lowercase letters, English underscores '_' and hyphens '-'. It is not allowed to be blank and shall not exceed 32 characters."
      description:
        type: string
        description: "Description of the cloud disk. It allows you to enter all characters under UTF-8 encoding, but no more than 256 characters."
      diskType:
        type: string
        description: "Disk Type, ssd or premium-hdd"
      diskSizeGB:
        type: integer
        description: "Disk Size, in GiB"
      status:
        type: string
        description: "Status of the Cloud Disk, creating, available, in-use, extending, restoring, deleting, deleted, error_create, error_delete, error_restore or error_extend"
      attachments:
        type: array
        items:
          $ref: "./DiskAttachment.yaml#/definitions/diskAttachment"
        description: "Attachment Information"
      snapshotId:
        type: string
        description: "Snapshot ID used to create a cloud disk"
      multiAttachable:
        type: boolean
        description: "Is multiple attachment True or False"
      createTime:
        type: string
        format: date-time
        description: "Cloud Disk Creation Time"
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: "Cloud Disk Billing Configuration"
      tags:
        type: array
        items:
          $ref: "./Tag.yaml#/definitions/tag"
        description: "Tag Information"
