swagger: "2.0"
info:
  version: "v1"
  title: Cloud Physical Server
  description: CPS Subnet Operation APIs

basePath: /regions/{regionId}

paths:
  "/subnet":
    ###################### Query Subnet ######################
    get:
      description: "Query Subnet "
      operationId: describeSubnet
      parameters:
        - name: az
          in: query
          required: true
          type: string
          description: "Availability Zone, as cn-east-1a; the availability zones supported by the Cloud Physical Servers in the region can be obtained by calling API (describeRegions)"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  subnet:
                    type: object
                    $ref: "../model/Subnet.yaml#/definitions/subnet"
                    description: Subnet Details
              requestId:
                type: string
        400:
          description: "Bad request"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID, the Region and Availability Zone Supported by the Cloud Physical Servers can be Obtained by Calling APIs (describeRegions)
  subnetId:
    name: subnetId
    in: path
    required: true
    type: string
    description: "Subnet ID"