swagger: "2.0"
definitions:
  instanceNetworkInterfaceAttachment:
    x-jdcloud-module: vm
    properties:
      deviceIndex:
        type: integer
        description: "Device Index"
      autoDelete:
        type: boolean
        description: "Indicates whether the network interface is deleted when deleting an instance, and the default is true, which cannot be changed currently"
      networkInterface:
        $ref: "./InstanceNetworkInterface.yaml#/definitions/instanceNetworkInterface"
        description: "Network Interface Specification"
