swagger: "2.0"
definitions:
  instanceTemplateDiskSpec:
    x-jdcloud-module: vm
    properties:
      diskType:
        type: string
        enum:
          - "ssd"
          - "premium-hdd"
        description: "Cloud disk type, value is ssd or premium-hdd"
      diskSizeGB:
        type: integer
        description: "The size of the cloud disk, unit is GiB; ssd type value range[20, 1000] GB, step size: 10G, premium-hdd type value range[20, 3000] GB, step size: 10G"
      snapshotId:
        type: string
        description: "Snapshot ID used to create Cloud Disk Service"