swagger: "2.0"
definitions:
  instance:
    x-jdcloud-module: vm
    title: Instance
    type: object
    properties:
      instanceId:
        type: string
        description: "VM ID"
      instanceName:
        type: string
        description: "VM Name"
      instanceType:
        type: string
        description: "Instance Type"
      vpcId:
        type: string
        description: "ID of Primary Network Interface’s VPC "
      subnetId:
        type: string
        description: "ID of Primary Network Interface’s Subnet "
      privateIpAddress:
        type: string
        description: "Primary IP address of primary network interface"
      elasticIpId:
        type: string
        description: "Elastic IP ID Associated to Primary IP of Primary Network Interface "
      elasticIpAddress:
        type: string
        description: "Elastic IP Associated to Primary IP of Primary Network Interface "
      status:
        type: string
        description: "Virtual Machine Status,<a href='http://docs.jdcloud.com/virtual-machines/api/vm_status'>Refer to virtual machine status</a>"
      description:
        type: string
        description: "VM Description"
      imageId:
        type: string
        description: "Image ID"
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: "System Disk Configuration"
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: "Data Disk Configuration"
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: "Primary Network Interface Configuration"
      secondaryNetworkInterfaces:
        type: array
        items:
          $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: "Secondary Network Interface Configuration"
      launchTime:
        type: string
        format: date-time
        description: "Creation Time"
      az:
        type: string
        description: "AZ of the VM"
      keyNames:
        type: array
        items:
          type: string
        minItems: 1
        description: "Key Pair Name"
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: "Billing Information"
      ag:
        $ref: "./Ag.yaml#/definitions/ag"
        description: "Availability Group, where an AG is used to create VM, the AG name can be displayed here"
      faultDomain:
        type: string
        description: "Error Domains in AGs"
      tags:
        type: array
        items:
          $ref: "./Tag.yaml#/definitions/tag"
        description: "Tag Information"
