swagger: "2.0"
definitions:
  instanceNetworkInterfaceAttachmentSpec:
    x-jdcloud-module: vm
    properties:
      deviceIndex:
        type: integer
        description: "Network device Index, and the primary network interface can only be 1"
      networkInterface:
        $ref: "../../vpc/model/NetworkInterfaceSpec.yaml#/definitions/networkInterfaceSpec"
        description: "Network Interface Specification"
