swagger: "2.0"
definitions:
  instanceTemplateData:
    x-jdcloud-module: vm
    properties:
      instanceType:
        type: string
        description: "Instance Type"
      vpcId:
        type: string
        description: "ID of Primary Network Interface’s VPC "
      imageId:
        type: string
        description: "Image ID"
      includePassword:
        type: boolean
        description: "Whether a custom password is contained in the start template, true: password contained, false: password not contained"
      systemDisk:
        $ref: "./InstanceTemplateDiskAttachment.yaml#/definitions/instanceTemplateDiskAttachment"
        description: "System Disk Information"
      dataDisks:
        type: array
        items:
          $ref: "./InstanceTemplateDiskAttachment.yaml#/definitions/instanceTemplateDiskAttachment"
        description: "The data disk information. The virtual machine with local disk as system disk can be attached with 8 data disks, and 7 data disks for the virtual machine with cloud disk as system disk."
      primaryNetworkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceTemplateNetworkInterfaceAttachmentSpec"
        description: "Primary Network Interface Information"
      elasticIp:
        $ref: "./InstanceTemplateElasticIp.yaml#/definitions/instanceTemplateElasticIp"
        description: "EIP specification associated with the primary IP of the primary network interface"
      keyNames:
        type: array
        items:
          type: string
        minItems: 1
        description: "Key Pair Name; only one is supported  currently"