swagger: "2.0"
definitions:
  instanceNetworkInterface:
    x-jdcloud-module: vm
    properties:
      networkInterfaceId:
        type: string
        description: "ENI ID"
      macAddress:
        type: string
        description: "Ethernet Address"
      vpcId:
        type: string
        description: "Virtual Network ID"
      subnetId:
        type: string
        description: "Subnet ID"
      securityGroups:
        type: array
        items:
          $ref: "./SecurityGroupSimple.yaml#/definitions/securityGroupSimple"
          description: "Security Group List"
      sanityCheck:
        type: integer
        description: "Source and target IP address verification, with value 0 or 1"
      primaryIp:
        $ref: "../../vpc/model/NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: "Network Interface Primary IP"
      secondaryIps:
        type: array
        description: "Network Interface Secondary IP"
        items:
          $ref: "../../vpc/model/NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
