swagger: "2.0"
definitions:
  instanceDiskAttachment:
    x-jdcloud-module: vm
    type: object
    properties:
      diskCategory:
        type: string
        description: |
          Disk classification, the local disk or data disk is taken.
          The system disk supports local disk or cloud disk. The system disk selects local Type, and the user must use the image localDisk type; if the system disk selects the cloud type, the user must use the image of the cloudDisk type.
          The data disk supports cloud disk only.
      autoDelete:
        type: boolean
        description: |
          Delete this disk with the VM automatically when the machine is deleted. The default value is true, which cannot be changed by local.
          This parameter does not take effect if the billing methond of the data disk in the VM is a monthly package.
          This parameter does not take effect if the data disk in the VM is a shared data disk.
      localDisk:
        $ref: "./LocalDisk.yaml#/definitions/localDisk"
        description: "Local Disk Configuration"
      cloudDisk:
        $ref: "../../disk/model/Disk.yaml#/definitions/disk"
        description: "Cloud Disk Configuration"
      deviceName:
        type: string
        description: "Data disk logical attaching point, value range: vda, vdb, vdc, vdd, vde, vdb, vdg, vdh, vdi"
      status:
        type: string
        description: Data disk attach status, value range: attaching,detaching,attached,detached,error_attach,error_detach